# Site/SEO settings
email: mayhem@drown.party
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Mayhem Drown
title: Drown Party

description: >
  写点什么，交个朋友
url: http://drown.party
default_img: /assets/images/seo.jpg

# Contact settings
contact_img: /assets/images/mail.jpg
formcarry: https://formcarry.com/s/2AwTVi-dpQCo

# Disqus settings
disqus: drown

# Author settings
author:
  - name: Mayhem Drown
    bio: 交个朋友
    url: http://drown.party

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
